### ISSUE TITLE
is there any way to manipulate the string 

### ISSUE THREAD

**Issue by tameemahmad** [khaled-alshamaa/ar-php#11]
get the word سَنَةٌ to be more generic by removing the last vowel ٌ to become سَنَة so it will match all versions like سَنَةٍ etc

And then make it more generic to get السَنَة including بالسَنَة

or simple after using `$Arabic->stripHarakat($content)` and then use all diacritics again

**Comment by khaled-alshamaa** [comment]
Thanks for your suggestion @tameemahmad, this feature will be included in the next version 6.2 of this library.
