### ISSUE TITLE
 إضافة ملف README.md باللغة العربية

### ISSUE THREAD

**Issue by atefBB** [khaled-alshamaa/ar-php#12]
<div dir="rtl">شكرا على المجهود الطيب. اقترح إضافة ملف README.md باللغة العربية.</div>

**Comment by khaled-alshamaa** [comment]
<div dir="rtl" align="justify">
تم، يمكنك مراجعة هذه الصفحة [هنا](https://github.com/khaled-alshamaa/ar-php/blob/master/README_ar.md)
</div>
