### ISSUE TITLE
Has the library the ability to normalize Arabic text?

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [khaled-alshamaa/ar-php#18]
<div dir="rtl">
هل مكتبة "PHP واللغة العربية" لديها إمكانية تنميط النصوص العربية Text Normalization ؟ إذا لم تكن فهذا فكرة جميلة لإضافتها للمكتبة..

**Comment by jhonny213** [comment]
شكرا لك أستاذنا الفاضل و شفاك الله و حفظك من كل سوء
تحياتي لكم

‫في السبت، 13 نوفمبر 2021 في 10:38 م تمت كتابة ما يلي بواسطة ‪Watheq
Alshowaiter‬‏ ***@***.***‬‏>:‬

**Comment by WatheqAlshowaiter** [comment]
بارك الله فيك أستاذ خالد وشفاك ورزقك الصحة والعافية والعطاء الدائم للمجتمع ..

**Comment by khaled-alshamaa** [comment]
$Arabic = new \ArPHP\I18N\Arabic();
    $text = 'آسِفـــةٌ لا تَنَبُّؤْ';

    $Arabic->setNorm('stripTatweel', true)
           ->setNorm('stripTanween', true)
           ->setNorm('stripShadda', true)
           ->setNorm('stripLastHarakat', true)
           ->setNorm('stripWordHarakat', true)
           ->setNorm('normaliseLamAlef', true)
           ->setNorm('normaliseAlef', true)
           ->setNorm('normaliseHamza', true)
           ->setNorm('normaliseTaa', true);

    $text = $Arabic->arNormalizeText($text);

**Comment by khaled-alshamaa** [comment]
قد أكون تعجّلت في إغلاق هذا النقاش قبل الحصول على رإي الأخ والصديق واثق أو أي مهتم آخر بهذه الدالة المطلوبة، سواء من ناحية الوظيفة أو طريقة التطبيق وسهولة الاستخدام والاستدعاء. 
خصوصا أن هذا الطلب بقي دون رد لمدة تزيد عن ٤ أشهر، لذا سأعيد فتح النقاش لمتابعة الحوار ومواصلة العمل على تحسين وإتقان المطلوب قبل أن يتم تضمينه في الإصدار القادم من المكتبة قريبا إن شاء الله.

**Comment by WatheqAlshowaiter** [comment]
@khaled-alshamaa 
أقترح وجود دالة لكل ما سبق من خيارات مثلا setNormِAll للاختصار ..

**Comment by khaled-alshamaa** [comment]
تم إضافة all كأحد الخيارات للوسيط form ضمن الطريقة/الدالة setNorm، لذا أصبح المطور قادرا على استخدام الاستدعاء التالي:
` 
$Arabic = new \ArPHP\I18N\Arabic();
$text = 'آسِفـــةٌ لا تَنَبُّؤْ';

$Arabic->setNorm('all', true)->setNorm('normaliseHamza', false)->setNorm('normaliseTaa', false);

$text = $Arabic->arNormalizeText($text);
`

لتكون النتيجة كالتالي: اسفة لا تنبؤ

**Comment by khaled-alshamaa** [comment]
أتوقع أن هذه الوظيفة لتنميط النصوص العربية أصبحت في صورة مبدئية قابلة للنشر ضمن الإصدار القادم، إن كنت توافق على ذلك صديقي واثق فأعلمني حتى نغلق هذا النقاش.

**Comment by WatheqAlshowaiter** [comment]
فعلا.. موافق عليها..
