### ISSUE TITLE
تذكير العدد وتأنيثه

### ISSUE THREAD

**Issue by ATablas** [khaled-alshamaa/ar-php#2]
الله يعطيكم العافية

في الملف التالي:

> src/data/ar_numbers.json

ضمن:
individual > male
و
individual > female
الأعداد من 3 إلى 19 عكس القاعدة
فعندما يكون المعدود مذكراً تكون هذه الأعداد مؤنثة والعكس بالعكس.

والأمر الآخر هو أن الهمزة في العدد 2 دائماً همزة وصل؛ هكذا مثلاً:
اثنان / اثنا عشر... إلخ

**Comment by khaled-alshamaa** [comment]
شكرا لك على التصويب، من المثير للاهتمام كيف غفلنا عن مثل هكذا خطأ أساسي كل هذه المدة!
لقد تم تصويب الخطأ في الملف المعني (شكرا لبنية المكتبة المرنة التي تراعي ذلك)، وسيتم تضمين التصويب في الإصدار القادم إن شاء الله. من جهة أخرى أرغب في إضافة إسمك إلى قائمة المساهمين ضمن سجل التعديلات كما جرت العادة والعرف، لذا يرجى التواصل معي بخصوص ذلك.
