### ISSUE TITLE
لدي مشكله في البحث في قواعد البيانات

### ISSUE THREAD

**Issue by Q8hma** [khaled-alshamaa/ar-php#26]
السلام عليكم ورحمة الله وبركاته 

لدي مشكله في بحث النتائج لا يبحث بالشبع أو التقريب

`SELECT voted,voters.id as voters_id,gad_num,gad_f_chart,full_name,family_name,age,voters.gender as gender,location.name as location_name,Trusted,Proved_by,CONCAT(School.Name, ' - ',Lajna.Name) as job_title,lajna_id FROM `voters` inner join location on Location_id=location.id inner join Lajna on Lajna.id=voters.lajna_id inner join School on Lajna.sid=School.id where 1=1 and ( REPLACE(voters.full_name, 'ـ', '') REGEXP 'ع(ا|أ|إ|آ)يش(ة|ه)') AND ( REPLACE(voters.full_name, 'ـ', '') REGEXP 'جم(ا|أ|إ|آ)ل') AND ( REPLACE(voters.full_name, 'ـ', '') REGEXP '(ا|أ|إ|آ)حمد') AND ( REPLACE(voters.full_name, 'ـ', '') REGEXP '((ا|أ|إ|آ)ل)?ه(ا|أ|إ|آ)ر(ون)?') ORDER BY `voters`.`gad_num`,full_name `

**Comment by Q8hma** [comment]
النتيجه صفر مع العلم أنه الاسم موجود ١٠٠% ولكن بأحرف 
ة و ئ وليس هـ و ي
وشكراً 

يرجى المساعده

**Comment by khaled-alshamaa** [comment]
أتوقع أن الاسم الذي تقصده والمتسبب في المشكلة التي تصفها هو "عائشة" في حين أن البحث يتم باستخدام كلمة "عايشه". حسنا، إن كان ذلك هو الحال، فالخوارزمية المستخدمة حاليا تستطيع إيجاد المطابقة مع كلمة "عائشه" (أي بإبدال التاء المربوطة في نهاية الكلمة بالهاء، وهو من الأخطاء الشائعة)، لكنها لا تراعي احتمال إبدال الهمزة على نبرة في متن الكلمة بالياء.

بعد قليل من التفكير، أجد أنها حالة شائعة بدورها وتستحق أن نأخذها في الحسبان، فهناك العديد من الحالات المشابهة مثل قائمة تكتب قايمة، وكذلك نائمة تكتب نايمة، وهكذا دواليك.. لذا سأقوم بتضمين هذا التعديل المقترح في الإصدار القادم من المكتبة والذي سيتم إصداره الشهر المقبل إن شاء الله.

في الختام، أشكرك على إهداء هذه الملاحظة لنا، فبمثل هكذا تفاعل ننمو ونكبر ونحسن من جودة عملنا ليكون متاحا في يد المطورين العرب لخدمة لغتنا العربية بشكل أفضل على منصات الإنترنت المختلفة.

**Comment by khaled-alshamaa** [comment]
إن احتجت إلى حل جزئي سريع دون انتظار الإصدار القادم من مكتبة PHP واللغة العربية، فيمكنك إضافة العنصر التالي:
```
     {
        "search": "/(\\S{1,})ئ(\\S{1,})/",
        "replace": "\\1(ئ|ي)\\2"
      },
```
إلى الملف `src/data/ar_query.json` 

برجاء إغلاق هذه الشكوى إن تم حل مشكلتك، إن لم يردني من طرفك أي تعليق خلال هذا الأسبوع سأقوم بإغلاق الشكوى تلقائيا.

**Comment by Q8hma** [comment]
شكراً لك
تم الحل وبنتظار التحديث الجديد

شكراً لك
