### ISSUE TITLE
واجهة مشكلة غريبة مع نص طويل

### ISSUE THREAD

**Issue by BechirAhmed** [khaled-alshamaa/ar-php#38]
لدي نص تم نسخه من الانترنت للتجربة فقط، 
 ---
تحديات عديدة تواجه حكومة ولد عبد الرحمن وتقف في طريق تنفيذ تعهدات رئيس الجمهورية التي اعلن عنها في حملته الدعائية الممهدة للانتخابات الرئاسية التي فاز بها قبل شهور من الان ولعل ابرز هذه التحديات تحدي الفساد النابع من سوء استخدام السلطة العامة من اجل مكاسب شخصية كاختلاس المال العام الذي عاد بقوة في المؤسسات العمومية والشركات وتفشي الرشوة في ادارات ومصالح الدولة حيث اصبح من الصعوبة بمكان ان تسحب مستخرجا من عقد ازدياد او بطاقة تعريف او شهادة وفاة من دون ان ترشي الحارس ثم البواب الذي يقف عند باب المكتب ثم المسؤول بطريقة فاضحة وهكذا.
---
وبعد عرضه في PDF الجملة تبدأ من وسط السطر ويتم تقطيعها 
لاحظ الصورة المرفق
<img width="784" alt="Screen Shot 2022-08-17 at 12 56 04" src="https://user-images.githubusercontent.com/18298101/185141053-a5b07c4b-832c-495b-b43c-c1027752af2d.png">
ة

**Comment by BechirAhmed** [comment]
I use this library with Laravel & dompdf
This is my code
```
$reportHtml = view('letter::app.pdf.template1', [])->render();
$arabic = new Arabic();
$p = $arabic->arIdentify($reportHtml);

for ($i = count($p) - 1; $i >= 0; $i -= 2) {
      $utf8ar = $arabic->utf8Glyphs(substr($reportHtml, $p[$i - 1], $p[$i] - $p[$i - 1]));
      $reportHtml = substr_replace($reportHtml, $utf8ar, $p[$i - 1], $p[$i] - $p[$i - 1]);
}

 $pdf = PDF::loadHTML($reportHtml);
```

**Comment by khaled-alshamaa** [comment]
عذرا أخي بشر على التأخر في الرد على شكواك هذه، برجاء مشاركتي محتوى المتغير `$reportHtml` ضمن ملف نصي بصيغة txt نظرا لأن الشيطان في التفاصيل كما يقولون، فأنا أشك بأحد أمرين، إما بسبب رموز إنتقال إلى سطر جديد بتنسيق Unix أو حتى Mac، أو قد تكون هناك واسمات HTML تتسبب في هذا التقسيم الغريب. لذلك أنا بحاجة إلى أن ألقي نظرة فاحصة أقرب على مدخلاتك وأكون قادرا على تكرار الخطأ الظاهر حتى أستطيع الإجابة أو تصويبه في الشيفرة البرمجية للمكتبة.

**Comment by BechirAhmed** [comment]
[reportHtml.txt](https://github.com/khaled-alshamaa/ar-php/files/9401827/reportHtml.txt)

هذا هو الملف، والنص موجود فيه ولما أظهر view بدون PDF النص يكون طبيعي بدون أي مشاكل

**Comment by BechirAhmed** [comment]
كما أن كلمة "للإنتخابات" تتغير، إذا وضعت همزة "للإ" يظهر رمز غريب، واذا حذفت الهمزة تصير بالشكل الواضح "لالانتخابات"

**Comment by khaled-alshamaa** [comment]
جاري العمل على حل هذه المشكلة، شكرا لك على تنبيهنا

**Comment by khaled-alshamaa** [comment]
أخي العزيز @BechirAhmed يمكنك استبدال شيفرتك البرمجية السابقة بالشيفرة البرمجية التالية والتي ستكون كفيلة بحل مشكلتك بشكل مرضي لكنها تحتاج منك أن تقوم بتحديد العدد الأقصى من المحارف التي يتسع لها السطر الواحد (مثلا 160 حرف كما في المثال التالي):
```php
$reportHtml = view('letter::app.pdf.template1', [])->render();
$arabic = new Arabic();
$p = $arabic->arIdentify($reportHtml);

$maxLineChr = 160;
$htmlOutput = substr($reportHtml, 0, $p[0]);

for ($i = 0; $i < count($p); $i += 2) {
    $utf8ar = $arabic->utf8Glyphs(substr($reportHtml, $p[$i], $p[$i+1] - $p[$i]), $maxLineChr);
    $lastEn = isset($p[$i+2]) ? $p[$i+2] : strlen($reportHtml);

    $htmlOutput .= str_replace("\n", "<br>\n", $utf8ar);
    $htmlOutput .= substr($reportHtml, $p[$i+1], $lastEn - $p[$i+1]);
}

$pdf = PDF::loadHTML($htmlOutput);
```
![2023-04-03 01_19_00-Letter - SNT-000001](https://user-images.githubusercontent.com/11270404/229384579-31a51f54-f4a9-4411-9d2a-dcf29b83af85.png)

أعتذر عن كل هذا التأخر بسبب كثرة إنشغالي في عملي، لكن كما يقول المثل: أن تصل متأخرا خير من أن لاتصل.

أرجو أن تقوم بتجربة هذا الحل من طرفك وتأكيد النتيجة حتى نقوم بإغلاق هذه الشكوى بنجاح، مع ملاحظة أنني سأقوم بإغلاقها نهاية هذا الأسبوع إن لم يردني من طرفكم أي إجابة، مفترضا أن الحل الذي قدمته أعلاه يفي بالغرض وقام بحل المشكلة موضوع الشكوى.

**Comment by BechirAhmed** [comment]
Hi @khaled-alshamaa , I've tried your solution but i got an error
<img width="1567" alt="Screenshot 2023-04-03 at 15 54 57" src="https://user-images.githubusercontent.com/18298101/229564677-289f472c-96c3-413c-b8a7-818aa77d08ac.png">

I use version 6.3.3

**Comment by khaled-alshamaa** [comment]
Try this hot fix for that line 2399:
https://github.com/khaled-alshamaa/ar-php/blob/341acd4d13020775e2cf43eee533e833c9b3d67d/src/Arabic.php#L2399

**Comment by khaled-alshamaa** [comment]
**_Please try my suggested solution using the latest version 6.3.4 that we released it recently._**

> أخي العزيز @BechirAhmed يمكنك استبدال شيفرتك البرمجية السابقة بالشيفرة البرمجية التالية والتي ستكون كفيلة بحل مشكلتك بشكل مرضي لكنها تحتاج منك أن تقوم بتحديد العدد الأقصى من المحارف التي يتسع لها السطر الواحد (مثلا 160 حرف كما في المثال التالي):
> 
> ```
> $reportHtml = view('letter::app.pdf.template1', [])->render();
> $arabic = new Arabic();
> $p = $arabic->arIdentify($reportHtml);
> 
> $maxLineChr = 160;
> $htmlOutput = substr($reportHtml, 0, $p[0]);
> 
> for ($i = 0; $i < count($p); $i += 2) {
>     $utf8ar = $arabic->utf8Glyphs(substr($reportHtml, $p[$i], $p[$i+1] - $p[$i]), $maxLineChr);
>     $lastEn = isset($p[$i+2]) ? $p[$i+2] : strlen($reportHtml);
> 
>     $htmlOutput .= str_replace("\n", "<br>\n", $utf8ar);
>     $htmlOutput .= substr($reportHtml, $p[$i+1], $lastEn - $p[$i+1]);
> }
> 
> $pdf = PDF::loadHTML($htmlOutput);
> ```
> 
> ![2023-04-03 01_19_00-Letter - SNT-000001](https://user-images.githubusercontent.com/11270404/229384579-31a51f54-f4a9-4411-9d2a-dcf29b83af85.png)
> 
> أعتذر عن كل هذا التأخر بسبب كثرة إنشغالي في عملي، لكن كما يقول المثل: أن تصل متأخرا خير من أن لاتصل.
> 
> أرجو أن تقوم بتجربة هذا الحل من طرفك وتأكيد النتيجة حتى نقوم بإغلاق هذه الشكوى بنجاح، مع ملاحظة أنني سأقوم بإغلاقها نهاية هذا الأسبوع إن لم يردني من طرفكم أي إجابة، مفترضا أن الحل الذي قدمته أعلاه يفي بالغرض وقام بحل المشكلة موضوع الشكوى.

**Comment by khaled-alshamaa** [comment]
@BechirAhmed, Did you try it using the latest version 6.3.4 of the library?
