### ISSUE TITLE
does not comply with psr-4 autoloading

### ISSUE THREAD

**Issue by ansadil** [khaled-alshamaa/ar-php#4]
`composer require khaled.alshamaa/ar-php`
_Using version ^5.5 for khaled.alshamaa/ar-php
./composer.json has been updated
Running composer update khaled.alshamaa/ar-php
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking khaled.alshamaa/ar-php (v5.5.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading khaled.alshamaa/ar-php (v5.5.1)
  - Installing khaled.alshamaa/ar-php (v5.5.1): Extracting archive
Generating optimized autoload files
**Class ArPHP\I18N\Arabic located in ./vendor/khaled.alshamaa/ar-php/src/arabic.php does not comply with psr-4 autoloading standard. Skipping.**
**Class App\AClass\I18N\I18N_Arabic located in ./app/AClass/I18N/Arabic.php does not comply with psr-4 autoloading standard. Skipping.**
**Class App\AClass\I18N\ArabicException located in ./app/AClass/I18N/Arabic.php does not comply with psr-4 autoloading standard. Skipping._**

`# composer dumpautoload`
_Generating optimized autoload files
**Class ArPHP\I18N\Arabic located in ./vendor/khaled.alshamaa/ar-php/src/arabic.php does not comply with psr-4 autoloading standard. Skipping._**

- in addition we could not manage the file path using new Laravel framework

**Comment by ansadil** [comment]
Here , After some revision of the packages we found that the file **arabic** starting with a Capital letter to match with class name **Arabic** which not comply with PSR4 standards.

Thank you

**Comment by khaled-alshamaa** [comment]
I merged suggested pull request by @devansh-webkul, then I released the new version 5.5.2 with required fix both in here at GitHub and there on Packagist. I hope this resolve this issue.
