### ISSUE TITLE
Bug when I use LAM ALEF as first two letters

### ISSUE THREAD

**Issue by mamprogr** [khaled-alshamaa/ar-php#46]
When I use the library with words starts with "لا" like:
لا يوجد
لانا
It cause "ErrorException Undefined index".

![image](https://user-images.githubusercontent.com/734475/195538049-4a68dbfc-c1f3-4aa0-aedb-b79b7ecb5b48.png)

Could you please fix it?

Thanks.

**Comment by khaled-alshamaa** [comment]
Thank you @mamprogr for reporting this bug. We already [fix it](https://github.com/khaled-alshamaa/ar-php/commit/1d2eaf9dbf3ccdf87c3e7ba211194f1bf1f81bb5) in the development version, and it will be included in the next release 6.3.1. soon.
