### ISSUE TITLE
Bug when I use Hindi numbers

### ISSUE THREAD

**Issue by mamprogr** [khaled-alshamaa/ar-php#47]
When I use the library with Hindi numbers like:
رقم الطالب ٢

It cause "ErrorException Undefined index".
![image](https://user-images.githubusercontent.com/734475/196777096-737a0789-6736-4406-ae19-c71fbeb0644d.png)

**Comment by khaled-alshamaa** [comment]
Thanks @mamprogr to report this bug, it has been fixed in the development version and this fix will be included in the next v6.3.1 release soon.
