### ISSUE TITLE
Bug when I use TANWEEN

### ISSUE THREAD

**Issue by mamprogr** [khaled-alshamaa/ar-php#48]
When I use the library with words has TANWEEN like:
درساً
جيد جداً
It cause "ErrorException Undefined index".
![image](https://user-images.githubusercontent.com/734475/197868962-25c5f600-88dc-4de8-b55c-df2e2422f6e1.png)

Could you please fix it?

Thanks.

**Comment by khaled-alshamaa** [comment]
Thank you @mamprogr for reporting this bug. We already fix it in the development version, and it will be included in the next release 6.3.1. soon.
