### ISSUE TITLE
Problem when using ( money2str ) function with lang:en

### ISSUE THREAD

**Issue by ahmedfawky** [khaled-alshamaa/ar-php#5]
Example :
$Arabic = new \ArPHP\I18N\Arabic();
$Arabic->setNumberFeminine(1);
$Arabic->setNumberFormat(1);
$Arabic->money2str(45522.21, 'SAR', 'en');

Gave me this error :  ( Undefined index: Halala )

**Comment by HazemNoor** [comment]
@ahmedfawky I think English is not fully supported in `money2str` method and this parameter needs to be removed and use `ar` only

**Comment by khaled-alshamaa** [comment]
Thanks @ahmedfawky  for your reported bug, it has been fixed now, see the related commit details, it was a copy/paste mistake!

@HazemNoor, well.. it has a very basic support for English language in money2str method because it is simply out of this package scope ;-)
