### ISSUE TITLE
consecutive occurrences of stopwords

### ISSUE THREAD

**Issue by khashabawy** [khaled-alshamaa/ar-php#52]
If we have a text that contains three stop words like  ( والتي قد لا )
the word ( قد) wont be removed
so I have to run the arCleanCommon two or more times

**Comment by khaled-alshamaa** [comment]
Well noted, thanks for reporting this bug. We will resolve it in the coming v6.3.1 that scheduled to be released on 18 Dec, 2022

**Comment by khaled-alshamaa** [comment]
Dear @khashabawy,

I resolved this reported issue of the consecutive occurrences of stopwords. There is no need for more than one pass to that **private** method arCleanCommon() anymore ;-)

AbdAllah, if you are using our library on the [soundeals](https://soundeals.com/) platform, I would appreciate it if you allowed us to list it [here](https://github.com/khaled-alshamaa/ar-php#where-it-has-been-used).

**Comment by khashabawy** [comment]
> Dear @khashabawy,
> 
> 
> 
> I resolved this reported issue of the consecutive occurrences of stopwords. There is no need for more than one pass to that **private** method arCleanCommon() anymore ;-)
> 
> 
> 
> AbdAllah, if you are using our library on the [soundeals](https://soundeals.com/) platform, I would appreciate it if you allowed us to list it [here](https://github.com/khaled-alshamaa/ar-php#where-it-has-been-used).
> 
> 

Of course Eng.Khalid, you can list it 👍
