### ISSUE TITLE
Unable to install any version above 6.0.0

### ISSUE THREAD

**Issue by DrAliRagab** [khaled-alshamaa/ar-php#56]
If trying to install any version above 6.0.0, Composer throw an error:
`Install of khaled.alshamaa/ar-php failed`
```
In Filesystem.php line 284:

  Could not delete [path]/vendor/composer/c2b443c4\khaled-alshamaa-ar-php-1f31229\docs\pwa\pwa.zip:
  This can be due to an antivirus or the Windows Search Indexer locking the file while they are analyzed
```

![Screenshot 2022-12-19 224358](https://user-images.githubusercontent.com/37520558/208518844-5281eb2e-9d18-4a1b-9a6c-00b10c99a7d0.png)

I am trying to install it on a Laravel project.

Tried to manually remove the file but it doesn't exist.

Finally, I rolled back to 6.0.0 version which installed successfully.

**Comment by muotaz** [comment]
A naive question:

Do you have an anti-virus on your Windows laptop or computer ?

**Comment by DrAliRagab** [comment]
> A naive question:
> 
> Do you have an anti-virus on your Windows laptop or computer ?

Sure, Kaspersky Total Security 21.
Tried to pause protection and re-install, with no success.

**Comment by muotaz** [comment]
Are you using XAMPP ?

**Comment by DrAliRagab** [comment]
> Are you using XAMPP ?

No

**Comment by muotaz** [comment]
I would appreciate it if you could share your stack details. 

But I honestly would try to restart the system in Safe Mode with Networking and try to reinstall. 
Another something you could try, is to scan the pwa.zip separately using Kaspersky just to be sure. 

I'd try that before delving into more deep investigation. 

Best of luck!

**Comment by DrAliRagab** [comment]
I don't know why, but finally it worked after restarting my PC.
Also I scanned pwa.zip with my antivirus and no issues.

Thanks @muotaz

**Comment by khaled-alshamaa** [comment]
Now this is what I can call a community! Thanks @muotaz for supporting @DrAliRagab and help in resolve the reported issue.. It is highly appreciated :-)

**Comment by muotaz** [comment]
@khaled-alshamaa 
You are more than welcomed!
