### ISSUE TITLE
خطأ: ظهور خطأ عند استخدام الأحرف (للإ) في بداية أي كلمة مثل (للإحسان)

### ISSUE THREAD

**Issue by thabetrighi** [khaled-alshamaa/ar-php#60]
مرحباً المهندس خالد، 
@khaled-alshamaa

عند استخدام الأحرف التالية (للإ) في بداية أي كلمة يظهر خطأ في الحزمة
أمثلة للجمل:
- دورة للإحسان
- للإضافة يجب عليك

- الخطأ:
![error](https://user-images.githubusercontent.com/123886811/217541384-d3be3a1f-4f6e-4951-8554-6871767c7703.PNG)

- مسار الملف: vendor\khaled.alshamaa\ar-php\src\Arabic.php

- موضع الخطأ في الدالة arGlyphsPreConvert
![err_02](https://user-images.githubusercontent.com/123886811/217541645-2f4a6cbe-8cc4-43b3-bb2a-c903c52d2cd8.PNG)

**بارك الله فيك**

**Comment by thabetrighi** [comment]
إختفاء الخطأ بعد آخر تحديث 6.3.2
فقط يظهر حرف لام متل في بداية الكلمة
![98755](https://user-images.githubusercontent.com/123886811/217560455-8cc87c49-615b-433b-ab44-8707febccd3e.PNG)

**Comment by khaled-alshamaa** [comment]
عذرا على التأخر في الرد، سأقوم بتصحيح هذا الخطأ قريبا جدا

**Comment by khaled-alshamaa** [comment]
أحاول تكرار الخطأ الذي أشرتم إليه دون أي نجاح في ذلك حتى الآن، علما أنني جربت الجمل التالية:

- دورة للإحسان
- للإضافة يجب عليك
- المتقدمة للاحتضان

![2023-04-01 01_18_06-Arabic Glyphs to Render Arabic Text](https://user-images.githubusercontent.com/11270404/229248934-1f794149-6b52-4435-aeca-c1320cdbecf2.png)

لذا إن استطعت أن تقدم مثال مع شيفرة برمجية لإعادة توليد الخطأ سأكون لك من الشاكرين.

**Comment by khaled-alshamaa** [comment]
صديقي العزيز @thabetrighi، إن لم تشاركني معلومات كافية لإعادة توليد الخطأ الذي أشرت إليه سابقا (النص، الشيفرة البرمجية، الخط المستخدم، الخ) حتى نهاية الإسبوع، فسأفترض أن المشكلة لم تعد موجودة مع الإصدار الأخير من المكتبة، وبالتالي سأغلق هذه الشكوى.

في حال تعذر عليك تجربتها والتواصل خلال الإسبوع وبالتالي وجدت هذه الشكوى مغلقة، برجاء عدم التردد بفتحها من جديد مع تقديم المعلومات اللازمة لإعادة توليد الخطأ، مما يمنحنا القدرة على تجربتها واكتشاف أسبابها ومن ثم حلها إن شاء الله.

**Comment by thabetrighi** [comment]
@khaled-alshamaa 
مرحباً حياك الله،
شكراً لك على الرد،
بالنسبة للمعطيات:
مستخدم الحزمة على مشروع لارفل
الحزمة: "atm-code/ar-php-laravel": "^1.7",
هذا النص المستخدم: 'دورة في تأهيل الأسر المتقدمة للاحتضان'
![ar_1](https://user-images.githubusercontent.com/123886811/229374029-24cbb3c7-e4b0-4cbc-9340-c81b5c3d0ee9.PNG)
![ar_2](https://user-images.githubusercontent.com/123886811/229374075-ad9da6f0-e20a-481b-a5d5-c6c87b72b91d.PNG)
![ar_3](https://user-images.githubusercontent.com/123886811/229374141-0a8dccf3-d911-41c0-a65c-8daf8f508b75.PNG)

**Comment by thabetrighi** [comment]
@khaled-alshamaa 
أهلاً المهندس خالد،
بارك الله فيك لقد إختفى الخطأ بعد التعديل الأخير يعطيك العافية.
شكراً لك.

![test-1](https://user-images.githubusercontent.com/123886811/229606882-075add95-13ce-47d1-b1f9-43378dccd6c3.PNG)

**Comment by khaled-alshamaa** [comment]
على الرحب والسعة، وأعتذر مجددا عن كل هذا التأخير في معالجة المشكلة المبلغ عنها، وأشكرك على تنبيهك لوجود هذا الخطأ
