### ISSUE TITLE
Implicit conversion from `float` to `int` when using `getPrayTime()` method

### ISSUE THREAD

**Issue by DrAliRagab** [khaled-alshamaa/ar-php#70]
![Screenshot 2023-09-23 132752](https://github.com/khaled-alshamaa/ar-php/assets/37520558/10f4ac33-7e9c-41bd-8791-40441d582cde)

When using `$arabic->getPrayTime()`, I got this warning.

I think this is because these 3 lines:
```php
$g = $g % 360 + ($g - ceil($g) + 1);

$q = $q % 360 + ($q - ceil($q) + 1);

$L = $L % 360 + ($L - ceil($L) + 1);
```

As php documentation says "Operands of modulo are converted to int before processing. For floating-point modulo, see `fmod()`" 
[Arithmetic Operators](https://www.php.net/manual/en/language.operators.arithmetic.php)

We can use `fmod()` function 
[fmod](https://www.php.net/manual/en/function.fmod.php)

```php
$g = fmod($g, 360) + ($g - ceil($g) + 1);

$q = fmod($q, 360) + ($q - ceil($q) + 1);

$L = fmod($L, 360) + ($L - ceil($L) + 1);
```

**Comment by khaled-alshamaa** [comment]
Thank you :-)
