### ISSUE TITLE
Urdu Support

### ISSUE THREAD

**Issue by zahoorsolangi** [khaled-alshamaa/ar-php#71]
It functions admirably for the Arabic language. Would it be possible to add support for Urdu characters in the next version?

**Comment by khaled-alshamaa** [comment]
Thank you, @zahoorsolangi, for your suggestion regarding Urdu character support. We agree that adding Urdu support to our utf8Glyphs() function is important. While we currently support the following Persian letters shared with the Urdu alphabet: پ, چ, ژ, and گ, we still need to include the following additional Urdu-specific letters: ڑ, ڈ, and ٹ.

To ensure accurate implementation, we would appreciate assistance from a native Urdu speaker. Could you please confirm if there are any other characters we should add? Your help in testing this feature would be greatly appreciated.

**Comment by khaled-alshamaa** [comment]
Well, I did my homework and found 2 extra letters as per the Wikipedia reference:
https://en.wikipedia.org/wiki/Urdu_alphabet#Differences_from_Persian_alphabet
