### ISSUE TITLE
Undefined array key "ٱ"

### ISSUE THREAD

**Issue by BouamraHiba** [khaled-alshamaa/ar-php#77]
![image](https://github.com/user-attachments/assets/af8d788a-ca03-418b-ae86-7fd6730a28d9)

How to solve this problem please

![image](https://github.com/user-attachments/assets/a4c7dfc0-1f6a-40f2-9062-ac10c4eaec3f)

@khaled-alshamaa

**Comment by khaled-alshamaa** [comment]
Dear @BouamraHiba, Thanks for reporting this issue 👍

We [expand character glyphs support](https://github.com/khaled-alshamaa/ar-php/commit/bef43ad187fa0c4cbeb16827c7497037cd88f125) in the utf8Glyphs() function to include all single letter variants listed in the [Arabic Presentation Forms-A](https://en.wikipedia.org/wiki/Arabic_Presentation_Forms-A) needed for Persian, Urdu, Sindhi, and Central Asian languages. This should resolve your reported issue as well.
